// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfMGLGGEpMFMaJQQvVRgPlH9uGrtfCPaw',
    appId: '1:520072344081:web:39b34deae622915c8bb7b0',
    messagingSenderId: '520072344081',
    projectId: 'praner-market',
    authDomain: 'praner-market.firebaseapp.com',
    storageBucket: 'praner-market.appspot.com',
    measurementId: 'G-HEM0WD1QNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7P4jfHqejBYUrC9zOVcVwbWWWoHbv-mY',
    appId: '1:520072344081:android:75442e3bcda8ee498bb7b0',
    messagingSenderId: '520072344081',
    projectId: 'praner-market',
    storageBucket: 'praner-market.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfystcwZLRo-_Ax5z7Gxeye4zEW4lC4ro',
    appId: '1:520072344081:ios:9526b02bbbab984e8bb7b0',
    messagingSenderId: '520072344081',
    projectId: 'praner-market',
    storageBucket: 'praner-market.appspot.com',
    iosBundleId: 'com.example.pranerMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfystcwZLRo-_Ax5z7Gxeye4zEW4lC4ro',
    appId: '1:520072344081:ios:9526b02bbbab984e8bb7b0',
    messagingSenderId: '520072344081',
    projectId: 'praner-market',
    storageBucket: 'praner-market.appspot.com',
    iosBundleId: 'com.example.pranerMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfMGLGGEpMFMaJQQvVRgPlH9uGrtfCPaw',
    appId: '1:520072344081:web:df865201cccfadcb8bb7b0',
    messagingSenderId: '520072344081',
    projectId: 'praner-market',
    authDomain: 'praner-market.firebaseapp.com',
    storageBucket: 'praner-market.appspot.com',
    measurementId: 'G-PYGJQEZQZ2',
  );
}
